export { default as Header } from "./Header";
export { default as HeroSection } from "./HeroSection";
export { default as AboutSection } from "./AboutSection";
export { default as FeaturesSection } from "./FeaturesSection";
export { default as MetiersSection } from "./MetiersSection";
export { default as AISection } from "./AISection";
export { default as StatisticsSection } from "./StatisticsSection";
export { default as ContactSection } from "./ContactSection";
export { default as Footer } from "./Footer";